language: python

python:
  - "2.7"

env:
  - DJANGO="django==1.5.6"

install:
  - pip install -r requirements.txt
  - pip install $DJANGO
  - pip install pytest-django factory-boy 

script:
  - py.test
